// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const NEXT_PUBLIC_SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ?? import.meta.env?.VITE_SUPABASE_URL ?? '';
const NEXT_PUBLIC_SUPABASE_ANON_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ??
  import.meta.env?.VITE_SUPABASE_ANON_KEY ??
  '';

const fallbackUrl = 'https://placeholder.supabase.co';
const fallbackAnonKey = 'anon-key-placeholder';

const resolvedUrl = NEXT_PUBLIC_SUPABASE_URL || fallbackUrl;
const resolvedAnonKey = NEXT_PUBLIC_SUPABASE_ANON_KEY || fallbackAnonKey;
const isBrowser = typeof window !== 'undefined' && typeof window.localStorage !== 'undefined';
const storage = isBrowser
  ? window.localStorage
  : ({
      length: 0,
      clear: () => {},
      getItem: () => null,
      key: () => null,
      removeItem: () => {},
      setItem: () => {},
    } as Storage);

if (!NEXT_PUBLIC_SUPABASE_URL || !NEXT_PUBLIC_SUPABASE_ANON_KEY) {
  console.warn(
    '[Rebellious Aging] Missing NEXT_PUBLIC_SUPABASE_URL or NEXT_PUBLIC_SUPABASE_ANON_KEY. Using placeholder values.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(resolvedUrl, resolvedAnonKey, {
  auth: {
    storage,
    persistSession: isBrowser,
    autoRefreshToken: isBrowser,
  }
});
